name: build

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version-file: .node-version

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libgtk-3-dev \
            libxdo-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf

    - name: Install NPM dependencies
      run: npm install --global npm@12.0.2 && npm ci

    - name: Build
      run: npm run tauri build -- -v -- --locked

    - name: Prepare ZIP
      run: |
        cd src-tauri/target/release

        for lib in libwebkit2gtk-* libjavascriptcoregtk-*; do
          for path in $(ldd nwmpublisher | awk '{print $3}' | grep "$lib"); do
            cp -v "$path" .
          done
        done

        patchelf --set-rpath '$ORIGIN' nwmpublisher

        zip -r nwmpublisher_linux64.zip nwmpublisher libsteam_api.so libwebkit2gtk-* libjavascriptcoregtk-*

    - name: Release
      uses: softprops/action-gh-release@v3
      with:
        body: |
          See the [changelog for ${{ github.ref_name }}](${{ github.server_url }}/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md) for release notes.
        files: src-tauri/target/release/nwmpublisher_linux64.zip
        fail_on_unmatched_files: true

  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version-file: .node-version

    - name: Install NPM dependencies
      run: npm install --global npm@12.0.2 && npm ci

    - name: Build
      run: npm run tauri build -- -v -- --locked
      env:
        RUSTFLAGS: -Ctarget-feature=+crt-static

    - name: Release
      uses: softprops/action-gh-release@v3
      with:
        body: |
          See the [changelog for ${{ github.ref_name }}](${{ github.server_url }}/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md) for release notes.
        files: src-tauri/target/release/bundle/msi/nwmpublisher_*.msi
        fail_on_unmatched_files: true

  build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v7

    - name: Install Rust targets
      working-directory: src-tauri
      run: rustup target add aarch64-apple-darwin x86_64-apple-darwin

    - uses: actions/setup-node@v7
      with:
        node-version-file: .node-version

    - name: Install NPM dependencies
      run: npm install --global npm@12.0.2 && npm ci

    - name: Build
      run: npm run tauri build -- --target universal-apple-darwin -v -- --locked

    - name: Copy Steamworks SDK to bundle
      run: cp src-tauri/lib/steam_api/redistributable_bin/osx/libsteam_api.dylib src-tauri/target/universal-apple-darwin/release/bundle/macos/nwmpublisher.app/Contents/MacOS/libsteam_api.dylib

    - name: Prepare ZIP
      run: |
        cd src-tauri/target/universal-apple-darwin/release/bundle/macos
        zip -r nwmpublisher_macOS.app.zip nwmpublisher.app

    - name: Release
      uses: softprops/action-gh-release@v3
      with:
        body: |
          See the [changelog for ${{ github.ref_name }}](${{ github.server_url }}/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md) for release notes.
        files: src-tauri/target/universal-apple-darwin/release/bundle/macos/nwmpublisher_macOS.app.zip
        fail_on_unmatched_files: true
